## DATA ANALYTICS NOTEBOOK

This notebook is created for learning, noting and prototyping purposes that will be later used in the application.

1. Importing Data
 
2. Descriptive Analytics 

3. Diagnostic Analytics

4. Predictive Analytics

5. Prescriptive Analytics

In [21]:
# libraries import
import pandas as pd
import kagglehub
import os

## The Dataset - Google Stock Market Data

The dataset is imported from kaggle. The description attached below:

    This data is collected from Yahoo Finance 2024

    Price: Close price of the stock
    1. Volume: Volume of the stock
    2. Date: Date of the stock
    3. Open: Open price of the stock
    4. High: High price of the stock
    5. Low: Low price of the stock
    6. Close: Close price of the stock
    7. Adj Close: Adjusted close price of the stock
    8. Ticker: Ticker symbol of the stock

In [25]:
#--- dataset import
path = kagglehub.dataset_download("itzusama/google-stock-market-data-2024")
dataFileName = 'GOOG.csv' 
dataPath = os.path.join(path, dataFileName)

#--- data frame
df = pd.read_csv(dataPath)
df

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.10)

,Price,Adj Close,Close,High,Low,Open,Volume
0,Ticker,GOOG,GOOG,GOOG,GOOG,GOOG,GOOG
1,2024-01-02,139.21810913085938,139.55999755859375,140.61500549316406,137.74000549316406,139.60000610351562,20071900
2,2024-01-03,140.01614379882812,140.36000061035156,141.08999633789062,138.42999267578125,138.60000610351562,18974300
3,2024-01-04,137.7018280029297,138.0399932861328,140.63499450683594,138.00999450683594,139.85000610351562,18253300
4,2024-01-05,137.0534210205078,137.38999938964844,138.80999755859375,136.85000610351562,138.3520050048828,15433200
...,...,...,...,...,...,...,...
229,2024-11-26,170.6199951171875,170.6199951171875,171.4949951171875,169.42999267578125,169.49000549316406,14937500
230,2024-11-27,170.82000732421875,170.82000732421875,171.13999938964844,169.6699981689453,170.67999267578125,12433400
231,2024-11-29,170.49000549316406,170.49000549316406,170.8699951171875,168.75,170.05999755859375,9250700
232,2024-12-02,172.97999572753906,172.97999572753906,173.60000610351562,170.27000427246094,170.32000732421875,16593400
233,2024-12-03,173.02000427246094,173.02000427246094,174.32000732421875,172.50999450683594,173.1199951171875,15721500

In [31]:
print('Labels',df.columns)
print('Size', df.shape)

Labels Index(['Price', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')
Size (234, 7)